-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (1,1960,'Italy','Damiano',FALSE,'Moretti');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (2,1986,'United Kingdom','John',TRUE,'Brown');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (3,1989,'Norway','Magnus',TRUE,'Carlsen');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (4,1942,'France','Amelie',FALSE,'Trindeux');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (5,2002,'Greece','Constantinos',TRUE,'Constantopoulos');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (6,1907,'United States','John',FALSE,'Jackson');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (7,1969,'China','Lee',FALSE,'Sin');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (8,1948,'Australia','Jake',FALSE,'Smith');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (9,1999,'Slovenia','Luka',TRUE,'Doncic');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (10,1955,'Japan','Tanaka',TRUE,'Mayumi');
-- insert into PEOPLE(ID, YOB, COUNTRY, FIRSTNAME, ISALIVE, LASTNAME) values (11,1972,'Japan','Takeuchi ',TRUE,'Junko');
--
--
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (1,'Do not watch this alone',136,'English','four',2016,'Are you alone ?');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (2,'Do watch this alone',146,'English','two',2018,'Are you alone ? 2');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (3,'A show about pirates',25,'Japanese','five',1998,'One Piece');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (4,'A show about pirates',25,'Japanese','five',2012,'One Piece, Marineford');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (5,'A show about pirates',24,'Japanese','five',2018,'One Piece, Dressrosa');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (6,'A show about ninjas',25,'Japanese','four',1999,'Naruto');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (7,'A show about ninjas',25,'Japanese','five',2001,'Naruto, Chounin Exams');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (8,'A show about ninjas',26,'Japanese','five',2011,'Naruto, Akatsuki');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (9,'Luca and Bugs Bunny ',113,'English','four',2026,'Space Jump 3');
-- insert into FILMS (ID, DESCRIPTION, DURATION, LANGUAGE, RATING, RELEASEYEAR, TITLE) values (10,'Best movie no one knows',129,'English','three',2014,'Peanut Butter');
--
--
-- insert into TVSHOWS(NUMBEROFEPISODES, SEASONS, ID) values (2,22,3);
-- insert into TVSHOWS(NUMBEROFEPISODES, SEASONS, ID) values (2,14,6);
--
--
-- insert into TVSHOWS_EPISODES(TVSHOW_ID, EPISODES_ID) values (3 ,4 );
-- insert into TVSHOWS_EPISODES(TVSHOW_ID, EPISODES_ID) values (3 ,5 );
-- insert into TVSHOWS_EPISODES(TVSHOW_ID, EPISODES_ID) values (6 ,8 );
-- insert into TVSHOWS_EPISODES(TVSHOW_ID, EPISODES_ID) values (6 ,7 );
--
-- insert into TVSHOWS(EPISODES, SEASONS, ID) values (123,15,3);
--
--
-- insert into TVSHOWS_NUMFILM(TVSHOW_ID, NUMFILM_ID) values (3 ,4 );
-- insert into TVSHOWS_NUMFILM(TVSHOW_ID, NUMFILM_ID) values (3 ,5 );

